SELECT id,
ARRAY_AGG(DISTINCT g ) AS txt_g,
MIN(type) AS type,
ARRAY_AGG(DISTINCT name) AS name,
ARRAY_AGG(DISTINCT name) AS txt_name,
MIN(description ) AS description,
ARRAY_AGG(DISTINCT contributor) AS txt_contributor,
ARRAY_AGG(DISTINCT description ) AS txt_description,
ARRAY_AGG(DISTINCT contenturl ) AS txt_distribution,
ARRAY_AGG(DISTINCT url ) AS txt_url,
ARRAY_AGG(DISTINCT temporalCoverage ) AS txt_temporalCoverage,
ARRAY_AGG(DISTINCT keywords ) AS txt_keywords,
ARRAY_AGG(DISTINCT courseName ) AS txt_courseName,
ARRAY_AGG(DISTINCT location ) AS txt_location,
ARRAY_AGG(DISTINCT iritype ) AS txt_iritype,
ARRAY_AGG(DISTINCT sameAs ) AS txt_sameAs,
ARRAY_AGG(DISTINCT citation ) AS txt_citation,
ARRAY_AGG(DISTINCT license ) AS txt_license,
ARRAY_AGG(DISTINCT version ) AS txt_version,
ARRAY_AGG(DISTINCT includedInDataCatalog ) AS txt_includedInDataCatalog,
ARRAY_AGG(DISTINCT memberOf ) AS txt_memberOf,
ARRAY_AGG(DISTINCT parentOrganization ) AS txt_parentOrganization,
ARRAY_AGG(DISTINCT knowsAbout ) AS txt_knowsAbout,
ARRAY_AGG(DISTINCT affiliation ) AS txt_affiliation,
ARRAY_AGG(DISTINCT category ) AS txt_category,
ARRAY_AGG(DISTINCT vehicleConfiguration ) AS txt_vehicleConfiguration,
ARRAY_AGG(DISTINCT vehicleSpecialUsage ) AS txt_vehicleSpecialUsage,
ARRAY_AGG(DISTINCT jobTitle ) AS txt_jobTitle,
ARRAY_AGG(DISTINCT knowsLanguage ) AS txt_knowsLanguage,
ARRAY_AGG(DISTINCT educationalCredentialAwarded ) AS txt_educationalCredentialAwarded,
ARRAY_AGG(DISTINCT author ) AS txt_author,
ARRAY_AGG(DISTINCT hasCourseInstance ) AS txt_hasCourseInstance,
ARRAY_AGG(DISTINCT areaServed ) AS txt_areaServed,
ARRAY_AGG(DISTINCT startDate ) AS txt_startDate,
ARRAY_AGG(DISTINCT endDate ) AS txt_endDate,
ARRAY_AGG(DISTINCT wkt ) AS txt_wkt,
MIN(DISTINCT geom ) AS the_geom,
MIN(DISTINCT lat )  AS txt_lat,
MIN(DISTINCT long )  AS txt_long,
ARRAY_AGG(DISTINCT place_name ) AS txt_place_name,
MIN(DISTINCT datePublished ) AS txt_datePublished,
MIN(DISTINCT dateModified ) AS txt_dateModified,
FROM arrow_table
GROUP BY id

