PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT (?s as ?id) ?g ?type ?name ?description ?contributor ?keywords
    ?variableMeasured ?provider
    ?contenturl ?courseName ?url
    ?location ?iritype ?wkt ?geom ?lat ?long ?place_name
    ?temporalCoverage ?datePublished ?dateModified
    ?sameAs ?citation ?license ?version ?includedInDataCatalog ?memberOf
    ?parentOrganization ?knowsAbout ?affiliation ?category
    ?vehicleConfiguration ?vehicleSpecialUsage
    ?jobTitle ?knowsLanguage ?educationalCredentialAwarded ?author
    ?hasCourseInstance ?location ?areaServed ?startDate ?endDate

WHERE {
     {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:description ?variableMeasured .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION  {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:description ?provider .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:name ?name .
            ?s schema:description ?description .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:contributor ?contributor .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?keywords .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:distribution ?distribution .
            ?distribution schema:contentUrl ?contenturl .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?irikeywords .
            ?irikeywords a schema:DefinedTerm .
            ?irikeywords schema:name ?keywords .
            FILTER (isIRI(?irikeywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?keywords .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?irikeywords .
            ?irikeywords a schema:DefinedTerm .
            ?irikeywords schema:name ?keywords .
            FILTER (isIRI(?irikeywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:url ?url .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:location ?location .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:address ?address .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Course> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:hasCourseInstance ?hasCourseInstance .
            ?hasCourseInstance schema:name ?courseName
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    }
}
