PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT (?s as ?id) ?g ?type ?name ?description ?contributor ?keywords
    ?variableMeasured ?provider
    ?contenturl ?courseName ?url
    ?location ?iritype ?wkt ?geom ?lat ?long ?place_name
    ?temporalCoverage ?datePublished ?dateModified
    ?sameAs ?citation ?license ?version ?includedInDataCatalog ?memberOf
    ?parentOrganization ?knowsAbout ?affiliation ?category
    ?vehicleConfiguration ?vehicleSpecialUsage
    ?jobTitle ?knowsLanguage ?educationalCredentialAwarded ?author
    ?hasCourseInstance ?location ?areaServed ?startDate ?endDate

WHERE {
    {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:name ?place_name .
            FILTER (!isIRI(?place_name)) .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:latitude ?lat .
            ?sc schema:longitude ?long .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:geo ?geo .
            ?geo a ?geotype .
            ?geo ?geompred ?geom .
            VALUES ?geompred { schema:box schema:polygon }
#            FILTER (!isIRI(?geom))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s geosparql:hasGeometry ?hasgeom .
            ?hasgeom geosparql:asWKT ?wkt
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:latitude ?lat .
            ?sc schema:longitude ?long .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:geo ?geo .
            ?geo a ?geotype .
            ?geo ?geompred ?geom .
            VALUES ?geompred { schema:box schema:polygon }
            #FILTER (!isIRI(?geom))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s geosparql:hasGeometry ?hasgeom .
            ?hasgeom geosparql:asWKT ?wkt
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:temporalCoverage ?temporalCoverage .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    }
}
