PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT (?s as ?id) ?g ?type ?name ?description ?contributor ?keywords
    ?variableMeasured ?provider
    ?contenturl ?courseName ?url
    ?location ?iritype ?wkt ?geom ?lat ?long ?place_name
    ?temporalCoverage ?datePublished ?dateModified
    ?sameAs ?citation ?license ?version ?includedInDataCatalog ?memberOf
    ?parentOrganization ?knowsAbout ?affiliation ?category
    ?vehicleConfiguration ?vehicleSpecialUsage
    ?jobTitle ?knowsLanguage ?educationalCredentialAwarded ?author
    ?hasCourseInstance ?location ?areaServed ?startDate ?endDate

WHERE {
  GRAPH ?g {
    BIND(<https://schema.org/Course> AS ?iritype)
    ?s rdf:type ?iritype .
    ?s schema:hasCourseInstance ?hasCourseInstance .
    OPTIONAL { ?hasCourseInstance schema:name ?courseName }
    BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
  }
}