PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <https://schema.org/>

SELECT ?s ?knowsAbout WHERE {
{
        graph ?g {
            BIND(<https://oceanexpert.org/expert/25843>  AS ?s)
            ?s rdf:type ?iritype .
            ?s schema:knowsAbout ?knowsAbout .
            FILTER (!isIRI(?knowsAbout) && !isBlank(?knowsAbout))
            FILTER (?knowsAbout != "")
            FILTER (?iritype IN (schema:Dataset, schema:Document, schema:Person))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://oceanexpert.org/expert/25843>  AS ?s)
             ?s rdf:type ?iritype .
            ?s schema:knowsAbout ?iriknowsAbout .
            ?iriknowsAbout schema:description ?knowsAbout .
            FILTER (isIRI(?iriknowsAbout))
            FILTER (?knowsAbout != "")
            FILTER (?iritype IN (schema:Dataset, schema:Document, schema:Person))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    }

}
